#!/usr/bin/env python3
"""
Bootstrap Cellpose Training - Round 2

Strategy:
1. Apply CLAHE contrast enhancement to improve cell/background separation
2. Use the Round 1 fine-tuned model (61.9% precision) to re-detect cells
3. Filter with manual annotations -> cleaner silver masks
4. Retrain Cellpose on improved labels + CLAHE-enhanced images

This addresses two problems simultaneously:
- Low-contrast images (P2963, P3090, etc.) where BG overlaps cell intensities
- Noisy silver masks from Round 1 (generated by 6% precision baseline model)
"""

import os
import sys
import json
import logging
import argparse
import numpy as np
import glob
from pathlib import Path
from typing import List, Dict, Tuple

sys.path.insert(0, str(Path(__file__).parent))

from config import PipelineConfig
from data_utils import (
    discover_all_data,
    read_multichannel_tiff,
    parse_cellcounter_xml,
)
from stage1_detection import get_mask_centroids

logger = logging.getLogger(__name__)


def apply_clahe(channel: np.ndarray, clip_limit: float = 2.0, grid_size: int = 64) -> np.ndarray:
    """
    Apply CLAHE (Contrast Limited Adaptive Histogram Equalization) to a single channel.
    
    Uses a tiled approach without requiring OpenCV:
      - Divides image into grid_size x grid_size tiles
      - Equalizes histogram within each tile with clipping
      - Bilinear interpolation between tiles for smooth result
    
    Args:
        channel: 2D array (any dtype, will be converted to uint8 range)
        clip_limit: Contrast limiting factor (higher = more contrast)
        grid_size: Tile size in pixels
    
    Returns:
        CLAHE-enhanced uint8 image
    """
    try:
        import cv2
        # If OpenCV is available, use it (much faster)
        if channel.dtype != np.uint8:
            lo = np.percentile(channel, 1)
            hi = np.percentile(channel, 99.5)
            if hi - lo < 1:
                return np.zeros_like(channel, dtype=np.uint8)
            ch = ((channel.astype(np.float32) - lo) / (hi - lo) * 255).clip(0, 255).astype(np.uint8)
        else:
            ch = channel.copy()
        
        clahe = cv2.createCLAHE(clipLimit=clip_limit, tileGridSize=(grid_size, grid_size))
        return clahe.apply(ch)
    except ImportError:
        # Fallback: simple percentile normalization with contrast stretch
        logger.warning("OpenCV not available, falling back to percentile normalization")
        ch = channel.astype(np.float32)
        lo = np.percentile(ch, 2)
        hi = np.percentile(ch, 98)
        if hi - lo < 1:
            return np.zeros_like(channel, dtype=np.uint8)
        ch = (ch - lo) / (hi - lo)
        ch = np.clip(ch * 255, 0, 255).astype(np.uint8)
        return ch


def estimate_neun_quality(neun: np.ndarray) -> dict:
    """
    Estimate the quality of the NeuN channel by measuring how well
    cell-like bright regions separate from background.
    
    Returns dict with:
        - contrast_ratio: bright/dim ratio (higher = better)
        - bg_uniformity: std of lower-half intensities (lower = better)
        - quality: 'good', 'ok', or 'poor'
    """
    # Use Otsu-like approach: find the threshold that separates two peaks
    lo = np.percentile(neun, 5)
    hi = np.percentile(neun, 95)
    mid = (lo + hi) / 2
    
    dim_pixels = neun[neun < mid]
    bright_pixels = neun[neun >= mid]
    
    if len(dim_pixels) == 0 or len(bright_pixels) == 0:
        return {'contrast_ratio': 1.0, 'bg_uniformity': 999, 'quality': 'poor'}
    
    contrast_ratio = bright_pixels.mean() / (dim_pixels.mean() + 1e-6)
    bg_uniformity = dim_pixels.std()
    
    if contrast_ratio > 1.8 and bg_uniformity < 60:
        quality = 'good'
    elif contrast_ratio > 1.3:
        quality = 'ok'
    else:
        quality = 'poor'
    
    return {
        'contrast_ratio': float(contrast_ratio),
        'bg_uniformity': float(bg_uniformity),
        'quality': quality,
    }


def prepare_cellpose_input_clahe(
    img: np.ndarray,
    source: str,
    config: PipelineConfig,
    clip_limit: float = 2.0,
    dapi_weight: str = 'adaptive',
) -> tuple:
    """
    Prepare NeuN + DAPI channels with CLAHE enhancement and adaptive
    DAPI weighting based on NeuN quality.
    
    When NeuN has poor contrast (high background, tile artifacts like P3137/P3142),
    DAPI provides a cleaner nuclear signal. This function can boost the DAPI
    contribution to help Cellpose find cells that are hard to see in NeuN alone.
    
    Cellpose channel convention:
      channels=[1, 2] means ch0=cytoplasm(NeuN), ch1=nucleus(DAPI)
      Cellpose uses BOTH channels internally — it's not just looking at NeuN.
      The nucleus channel helps define cell boundaries and seed detection.
    
    Strategy for poor-NeuN cases:
      Instead of changing channel weights (which Cellpose handles internally),
      we improve the NeuN channel itself by:
      1. CLAHE to boost local contrast
      2. DAPI-guided background subtraction: suppress NeuN background in
         regions where DAPI shows no nuclear signal (non-cell regions)
    
    Args:
        img: (C, H, W) multi-channel image
        source: 'LR' or 'MAYO'
        config: PipelineConfig
        clip_limit: CLAHE clip limit
        dapi_weight: 'adaptive' (auto-detect quality), 'none' (no DAPI guidance),
                     or float (manual weight, e.g., 0.3)
    
    Returns:
        (image, quality_info) where:
          image: (H, W, 2) uint8 array [NeuN_enhanced, DAPI_CLAHE]
          quality_info: dict with contrast metrics
    """
    channel_map = config.get_channel_map(source)
    neun_idx = channel_map["NeuN"]
    dapi_idx = channel_map["DAPI"]
    
    neun = img[neun_idx].astype(np.float32)
    dapi = img[dapi_idx].astype(np.float32)
    
    # Assess NeuN quality
    quality_info = estimate_neun_quality(neun)
    
    # Apply CLAHE to both channels
    neun_clahe = apply_clahe(neun, clip_limit=clip_limit)
    dapi_clahe = apply_clahe(dapi, clip_limit=clip_limit)
    
    # DAPI-guided NeuN enhancement for poor-quality cases
    if dapi_weight == 'adaptive':
        if quality_info['quality'] == 'poor':
            weight = 0.3  # Strong DAPI guidance
        elif quality_info['quality'] == 'ok':
            weight = 0.15  # Mild DAPI guidance
        else:
            weight = 0.0   # No guidance needed
    elif dapi_weight == 'none':
        weight = 0.0
    else:
        weight = float(dapi_weight)
    
    if weight > 0:
        # DAPI-guided background suppression:
        # Create a "cell likelihood" mask from DAPI (nuclear stain is cleaner)
        # Then blend: enhanced_NeuN = NeuN_clahe * (1-w) + NeuN_clahe * dapi_mask * w
        # This suppresses NeuN background noise where there's no DAPI signal
        dapi_norm = dapi_clahe.astype(np.float32) / 255.0
        
        # Soft mask: threshold DAPI to find nuclear regions, then dilate slightly
        # to cover cytoplasm around nuclei
        dapi_thresh = np.percentile(dapi_norm[dapi_norm > 0], 30) if np.any(dapi_norm > 0) else 0.1
        dapi_mask = np.clip((dapi_norm - dapi_thresh) / (1.0 - dapi_thresh + 1e-6), 0, 1)
        
        # Smooth the mask to avoid hard edges
        from scipy.ndimage import gaussian_filter
        dapi_mask_smooth = gaussian_filter(dapi_mask, sigma=5.0)
        dapi_mask_smooth = np.clip(dapi_mask_smooth * 2, 0, 1)  # boost
        
        # Blend: keep NeuN signal where DAPI confirms cells, suppress elsewhere
        neun_f = neun_clahe.astype(np.float32) / 255.0
        neun_enhanced = neun_f * (1.0 - weight) + neun_f * dapi_mask_smooth * weight
        # Re-normalize
        if neun_enhanced.max() > 0:
            neun_enhanced = (neun_enhanced / neun_enhanced.max() * 255).clip(0, 255).astype(np.uint8)
        else:
            neun_enhanced = neun_clahe
        
        quality_info['dapi_weight_applied'] = weight
        quality_info['enhancement'] = 'dapi_guided'
        
        return np.stack([neun_enhanced, dapi_clahe], axis=-1), quality_info
    
    quality_info['dapi_weight_applied'] = 0.0
    quality_info['enhancement'] = 'clahe_only'
    
    return np.stack([neun_clahe, dapi_clahe], axis=-1), quality_info


def run_detection_with_finetuned(
    image: np.ndarray,
    model_path: str,
    diameter: float = 30.0,
    flow_threshold: float = 0.4,
    cellprob_threshold: float = 0.0,
) -> Tuple[np.ndarray, np.ndarray]:
    """
    Run detection using a fine-tuned Cellpose model.
    
    Returns:
        masks: (H, W) label mask
        centroids: (N, 2) array of (x, y) centroids
    """
    from cellpose import models
    
    model = models.CellposeModel(pretrained_model=model_path, gpu=True)
    
    outputs = model.eval(
        image,
        diameter=diameter,
        channels=[1, 2],
        flow_threshold=flow_threshold,
        cellprob_threshold=cellprob_threshold,
    )
    # Cellpose v4 returns (masks, flows, styles); older versions return 4 values.
    masks = outputs[0]
    
    centroids = get_mask_centroids(masks)
    
    return masks, centroids


def match_and_filter_masks(
    masks: np.ndarray,
    centroids: np.ndarray,
    manual_points: np.ndarray,
    match_radius: float = 30.0,
) -> Tuple[np.ndarray, dict]:
    """
    Match detected masks against manual annotations and keep only matched ones.
    
    Returns:
        filtered_masks: (H, W) with only matched cells
        stats: matching statistics
    """
    from scipy.spatial.distance import cdist
    
    if len(centroids) == 0 or len(manual_points) == 0:
        return np.zeros_like(masks), {
            'detected': len(centroids),
            'manual': len(manual_points),
            'matched': 0,
            'precision': 0.0,
            'recall': 0.0,
        }
    
    # Compute distances
    dists = cdist(centroids, manual_points)
    
    # Greedy matching 
    matched_det = set()
    matched_man = set()
    
    # Sort by distance for better matching
    pairs = []
    for i in range(len(centroids)):
        for j in range(len(manual_points)):
            if dists[i, j] < match_radius:
                pairs.append((dists[i, j], i, j))
    pairs.sort()
    
    for dist, i, j in pairs:
        if i not in matched_det and j not in matched_man:
            matched_det.add(i)
            matched_man.add(j)
    
    # Build filtered mask with only matched cells
    # Need to map centroid indices to mask cell IDs
    cell_ids = []
    for cell_id in range(1, masks.max() + 1):
        ys, xs = np.where(masks == cell_id)
        if len(xs) > 0:
            cell_ids.append(cell_id)
    
    # cell_ids[i] corresponds to centroids[i]
    filtered_masks = np.zeros_like(masks)
    new_id = 1
    for i in matched_det:
        if i < len(cell_ids):
            old_id = cell_ids[i]
            filtered_masks[masks == old_id] = new_id
            new_id += 1
    
    n_det = len(centroids)
    n_man = len(manual_points)
    n_match = len(matched_det)
    
    return filtered_masks, {
        'detected': n_det,
        'manual': n_man,
        'matched': n_match,
        'precision': n_match / n_det if n_det > 0 else 0,
        'recall': n_match / n_man if n_man > 0 else 0,
    }


def generate_silver_masks_v2(
    config: PipelineConfig,
    output_dir: str,
    finetuned_model_path: str,
    clip_limit: float = 2.0,
    flow_threshold: float = 0.4,
    cellprob_threshold: float = 0.0,
) -> List[Dict]:
    """
    Generate Round 2 silver masks using:
    - CLAHE-enhanced images (better contrast)
    - Fine-tuned model (much higher precision than baseline)
    """
    os.makedirs(output_dir, exist_ok=True)
    all_cases = discover_all_data(config)
    results = []
    
    logger.info(f"Generating v2 silver masks for {len(all_cases)} cases")
    logger.info(f"  CLAHE clip_limit={clip_limit}")
    logger.info(f"  Model: {finetuned_model_path}")
    logger.info(f"  flow_threshold={flow_threshold}, cellprob_threshold={cellprob_threshold}")
    
    for i, case in enumerate(all_cases):
        case_id = case['case_id']
        logger.info(f"\n[{i+1}/{len(all_cases)}] Processing {case_id} ({case['source']})...")
        
        # Read image
        img = read_multichannel_tiff(case['tif_path'])
        
        # Prepare with CLAHE + adaptive DAPI guidance
        cp_input, quality_info = prepare_cellpose_input_clahe(img, case['source'], config, clip_limit)
        logger.info(f"  Image shape: {cp_input.shape}, range: [{cp_input.min()}, {cp_input.max()}]")
        logger.info(f"  NeuN quality: {quality_info['quality']} (contrast={quality_info['contrast_ratio']:.2f}, "
                    f"enhancement={quality_info['enhancement']}, dapi_weight={quality_info['dapi_weight_applied']:.2f})")
        
        # Run detection with fine-tuned model on CLAHE image
        masks, centroids = run_detection_with_finetuned(
            cp_input, finetuned_model_path,
            flow_threshold=flow_threshold,
            cellprob_threshold=cellprob_threshold,
        )
        logger.info(f"  Detected {len(centroids)} cells (fine-tuned + CLAHE)")
        
        # Load manual annotations
        marker_types = parse_cellcounter_xml(case['xml_path'])
        manual_neun = marker_types.get(1, {}).get('points', np.zeros((0, 2)))
        logger.info(f"  Manual NeuN points: {len(manual_neun)}")
        
        # Match and filter
        filtered_masks, stats = match_and_filter_masks(
            masks, centroids, manual_neun, match_radius=config.match_radius_px
        )
        
        n_kept = filtered_masks.max()
        logger.info(f"  Kept {n_kept} / {stats['detected']} masks "
                    f"(P={stats['precision']:.3f}, R={stats['recall']:.3f})")
        
        # Save CLAHE-enhanced image and filtered masks
        img_path = os.path.join(output_dir, f"{case_id}_img.npy")
        mask_path = os.path.join(output_dir, f"{case_id}_mask.npy")
        np.save(img_path, cp_input)        # (H, W, 2) uint8 CLAHE
        np.save(mask_path, filtered_masks)  # (H, W) int32
        
        results.append({
            'case_id': case_id,
            'source': case['source'],
            'img_path': img_path,
            'mask_path': mask_path,
            'cellpose_count': stats['detected'],
            'manual_count': stats['manual'],
            'silver_count': int(n_kept),
            'precision': stats['precision'],
            'recall': stats['recall'],
            'neun_quality': quality_info['quality'],
            'contrast_ratio': quality_info['contrast_ratio'],
            'dapi_weight_applied': quality_info['dapi_weight_applied'],
            'enhancement': quality_info['enhancement'],
        })
    
    # Save manifest
    manifest_path = os.path.join(output_dir, "silver_masks_manifest.json")
    with open(manifest_path, 'w') as f:
        json.dump(results, f, indent=2)
    
    return results


def finetune_cellpose_v2(
    silver_mask_dir: str,
    output_model_dir: str,
    n_epochs: int = 200,
    learning_rate: float = 0.0001,
    weight_decay: float = 0.1,
    batch_size: int = 8,
    pretrained_model: str = "cpsam",
    use_gpu: bool = True,
    test_fraction: float = 0.15,
    seed: int = 42,
):
    """
    Fine-tune Cellpose Round 2 with:
    - Cleaner silver masks (from fine-tuned model)
    - CLAHE-enhanced images
    - More epochs, tuned hyperparameters
    """
    from cellpose import models, train
    
    os.makedirs(output_model_dir, exist_ok=True)
    
    # Load manifest
    manifest_path = os.path.join(silver_mask_dir, "silver_masks_manifest.json")
    with open(manifest_path, 'r') as f:
        manifest = json.load(f)
    
    # Filter out cases with too few cells
    manifest = [e for e in manifest if e['silver_count'] >= 10]
    logger.info(f"Using {len(manifest)} images with >= 10 cells")
    
    # Split
    np.random.seed(seed)
    np.random.shuffle(manifest)
    n_test = max(1, int(len(manifest) * test_fraction))
    
    train_images, train_masks = [], []
    test_images, test_masks = [], []
    
    for entry in manifest[:-n_test]:
        img = np.load(entry['img_path'])
        mask = np.load(entry['mask_path'])
        train_images.append(img)
        train_masks.append(mask)
    
    for entry in manifest[-n_test:]:
        img = np.load(entry['img_path'])
        mask = np.load(entry['mask_path'])
        test_images.append(img)
        test_masks.append(mask)
    
    total_train_cells = sum(m.max() for m in train_masks)
    total_test_cells = sum(m.max() for m in test_masks)
    logger.info(f"Train: {len(train_images)} images, {total_train_cells} cells")
    logger.info(f"Test: {len(test_images)} images, {total_test_cells} cells")
    
    # Initialize model
    model = models.CellposeModel(gpu=use_gpu, pretrained_model=pretrained_model)
    
    logger.info(f"Training for {n_epochs} epochs...")
    logger.info(f"  LR={learning_rate}, WD={weight_decay}, BS={batch_size}")
    
    filename, train_losses, test_losses = train.train_seg(
        net=model.net,
        train_data=train_images,
        train_labels=train_masks,
        test_data=test_images if test_images else None,
        test_labels=test_masks if test_masks else None,
        save_path=output_model_dir,
        save_every=50,
        n_epochs=n_epochs,
        learning_rate=learning_rate,
        weight_decay=weight_decay,
        batch_size=batch_size,
        min_train_masks=1,
        model_name="cellpose_finetuned_v2",
    )
    
    logger.info(f"Model saved to: {filename}")
    logger.info(f"Final train loss: {train_losses[-1]:.4f}")
    if test_losses is not None and len(test_losses) > 0:
        best_epoch = np.argmin(test_losses)
        logger.info(f"Best test loss: {test_losses[best_epoch]:.4f} (epoch {best_epoch + 1})")
    
    # Save info
    info = {
        'round': 2,
        'base_model': pretrained_model,
        'n_epochs': n_epochs,
        'learning_rate': learning_rate,
        'weight_decay': weight_decay,
        'batch_size': batch_size,
        'n_train_images': len(train_images),
        'n_test_images': len(test_images),
        'total_train_cells': int(total_train_cells),
        'total_test_cells': int(total_test_cells),
        'clahe_enhanced': True,
        'model_path': str(filename),
        'final_train_loss': float(train_losses[-1]),
        'final_test_loss': float(test_losses[-1]) if (test_losses is not None and len(test_losses) > 0) else None,
    }
    with open(os.path.join(output_model_dir, "finetune_v2_info.json"), 'w') as f:
        json.dump(info, f, indent=2)
    
    return filename, train_losses, test_losses


def evaluate_model(
    model_path: str,
    image: np.ndarray,
    manual_points: np.ndarray,
    label: str,
    match_radius: float = 30.0,
):
    """Quick evaluation of a model on a single image."""
    masks, centroids = run_detection_with_finetuned(image, model_path)
    _, stats = match_and_filter_masks(masks, centroids, manual_points, match_radius)
    
    print(f"\n{label}:")
    print(f"  Detected: {stats['detected']}")
    print(f"  Matched: {stats['matched']} / {stats['manual']}")
    print(f"  Precision: {stats['precision']:.3f}")
    print(f"  Recall: {stats['recall']:.3f}")
    f1 = 2 * stats['precision'] * stats['recall'] / (stats['precision'] + stats['recall']) if (stats['precision'] + stats['recall']) > 0 else 0
    print(f"  F1: {f1:.3f}")
    
    return stats


def main():
    parser = argparse.ArgumentParser(description="Bootstrap Cellpose v2 with CLAHE")
    parser.add_argument("--skip_mask_gen", action="store_true")
    parser.add_argument("--skip_training", action="store_true")
    parser.add_argument("--clip_limit", type=float, default=2.0)
    parser.add_argument("--n_epochs", type=int, default=200)
    parser.add_argument("--lr", type=float, default=0.0001)
    parser.add_argument("--weight_decay", type=float, default=0.1)
    parser.add_argument("--batch_size", type=int, default=8)
    parser.add_argument("--pretrained_model", type=str, default=None,
                        help="Base model for training. Default: V1 fine-tuned model")
    parser.add_argument("--cellprob_threshold", type=float, default=0.0,
                        help="Cellprob threshold for detection during silver mask generation. "
                             "Lower values (e.g. -2.0) catch more dim cells but more FPs.")
    parser.add_argument("--mask_suffix", type=str, default="",
                        help="Suffix for silver mask dir (e.g. '_lowthresh'). "
                             "Keeps different mask sets separate.")
    args = parser.parse_args()
    
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(message)s",
    )
    
    config = PipelineConfig()
    
    # Paths
    v1_model = os.path.join(config.output_dir, "cellpose_finetuned", "model", "models", "cellpose_finetuned_neun_dapi")
    v2_output = os.path.join(config.output_dir, "cellpose_finetuned_v2")
    mask_dir_name = f"silver_masks_v2{args.mask_suffix}"
    v2_masks_dir = os.path.join(v2_output, mask_dir_name)
    model_dir_name = f"model{args.mask_suffix}"
    v2_model_dir = os.path.join(v2_output, model_dir_name)
    
    print("=" * 70)
    print("CELLPOSE BOOTSTRAP ROUND 2")
    print("  - CLAHE contrast enhancement")
    print("  - Re-detect with fine-tuned model (Round 1)")
    print("  - Retrain on cleaner labels")
    print("=" * 70)
    
    # =========================================================================
    # Step 1: Generate v2 silver masks with CLAHE + fine-tuned model
    # =========================================================================
    if not args.skip_mask_gen:
        print(f"\n{'='*70}")
        print("STEP 1: Generating v2 silver masks (CLAHE + fine-tuned model)")
        print(f"{'='*70}")
        
        results = generate_silver_masks_v2(
            config, v2_masks_dir, v1_model,
            clip_limit=args.clip_limit,
            cellprob_threshold=args.cellprob_threshold,
        )
        print(f"  cellprob_threshold={args.cellprob_threshold}")
        
        total_silver = sum(r['silver_count'] for r in results)
        total_manual = sum(r['manual_count'] for r in results)
        avg_precision = np.mean([r['precision'] for r in results if r['cellpose_count'] > 0])
        avg_recall = np.mean([r['recall'] for r in results if r['manual_count'] > 0])
        
        print(f"\nv2 Silver masks summary:")
        print(f"  Total cells: {total_silver} from {len(results)} images")
        print(f"  Coverage: {total_silver}/{total_manual} ({100*total_silver/total_manual:.1f}%)")
        print(f"  Avg precision: {avg_precision:.3f}")
        print(f"  Avg recall: {avg_recall:.3f}")
    else:
        print("Skipping mask generation")
    
    # =========================================================================
    # Step 2: Retrain Cellpose on v2 silver masks
    # =========================================================================
    if not args.skip_training:
        print(f"\n{'='*70}")
        print("STEP 2: Fine-tuning Cellpose Round 2")
        print(f"{'='*70}")
        
        # Use V1 model as starting point (much better than cpsam from scratch)
        base_model = args.pretrained_model if args.pretrained_model else v1_model
        if not os.path.exists(base_model):
            logger.warning(f"Base model {base_model} not found, falling back to cpsam")
            base_model = "cpsam"
        print(f"  Base model: {base_model}")
        print(f"  LR={args.lr}, WD={args.weight_decay}")
        
        model_path, train_losses, test_losses = finetune_cellpose_v2(
            silver_mask_dir=v2_masks_dir,
            output_model_dir=v2_model_dir,
            n_epochs=args.n_epochs,
            learning_rate=args.lr,
            weight_decay=args.weight_decay,
            batch_size=args.batch_size,
            pretrained_model=base_model,
        )
        
        print(f"\nv2 model saved to: {model_path}")
    
    # =========================================================================
    # Step 3: Quick evaluation on test case
    # =========================================================================
    print(f"\n{'='*70}")
    print("STEP 3: Evaluation on P3044_C12")
    print(f"{'='*70}")
    
    eval_case = "P3044_C12"
    eval_dir = Path("/fslustre/qhs/ext_chen_yuheng_mayo_edu/Cell_Counting_Proj/multiple_channel_model/Counting_Atypical_LR_MAYO") / eval_case
    
    # Load test image with CLAHE + adaptive DAPI guidance
    from data_utils import read_multichannel_tiff
    eval_img = read_multichannel_tiff(str(list(eval_dir.glob("StitchedROI-*.tif"))[0]))
    eval_input_clahe, eval_quality = prepare_cellpose_input_clahe(eval_img, 'MAYO', config, args.clip_limit)
    print(f"NeuN quality: {eval_quality['quality']} (contrast={eval_quality['contrast_ratio']:.2f}, "
          f"dapi_weight={eval_quality['dapi_weight_applied']:.2f})")
    
    # Load without CLAHE for comparison
    from stage1_detection import get_cellpose_input
    eval_input_orig = get_cellpose_input(eval_img, 'MAYO', config)
    
    # Load manual points
    marker_types = parse_cellcounter_xml(str(list(eval_dir.glob("CellCounter_*.xml"))[0]))
    manual_pts = marker_types.get(1, {}).get('points', np.zeros((0, 2)))
    print(f"Manual points: {len(manual_pts)}")
    
    # Evaluate v1 model (no CLAHE)
    evaluate_model(v1_model, eval_input_orig, manual_pts, "Round 1 model (no CLAHE)")
    
    # Evaluate v1 model (with CLAHE)
    evaluate_model(v1_model, eval_input_clahe, manual_pts, "Round 1 model + CLAHE")
    
    # Evaluate v2 model (with CLAHE)
    v2_model_path = os.path.join(v2_model_dir, "models", "cellpose_finetuned_v2")
    # Also check default model dir if suffix is used
    v2_model_path_default = os.path.join(v2_output, "model", "models", "cellpose_finetuned_v2")
    if os.path.exists(v2_model_path):
        evaluate_model(v2_model_path, eval_input_clahe, manual_pts, f"Round 2 model + CLAHE ({model_dir_name})")
    elif args.mask_suffix and os.path.exists(v2_model_path_default):
        evaluate_model(v2_model_path_default, eval_input_clahe, manual_pts, "Round 2 model + CLAHE (default)")
    else:
        print(f"\nv2 model not found at {v2_model_path}")
    
    print(f"\n{'='*70}")
    print("BOOTSTRAP ROUND 2 COMPLETE")
    print(f"{'='*70}")


if __name__ == "__main__":
    main()
